dist: xenial
language: python

addons:
 apt:
  packages:
   - snmp


before_script:
 - sudo pip install snmpsim
 - which snmpsimd.py
 - sudo snmpsimd.py --data-dir=tests/snmp_data --process-user=nobody --process-group=nogroup --agent-udpv4-endpoint=127.0.0.1:161

script:
 - snmpwalk -c public 127.0.0.1