language: sh
os: windows

before_install:
  - choco upgrade chocolatey
  - choco install python
  #- choco install pywin32
  #- python -m pip install pyinstaller
  - PYEXE = $ChocolateyInstall/bin/python.exe
install:
  #- python -m pip install pywin32
  - $PYEXE -V
  - where python
  - dir %ChocolateyInstall%\\bin
  # - set
