dist: bionic
language: python
python: 3.6

addons:
 apt:
  packages:
   - snmp
   - python3-pip

install:
 - git clone https://github.com/etingof/snmpsim.git

before_script:
 - sudo which pip3
 - pip install snmpsim
 - sudo -H pip3 install snmpsim
 - sudo which snmpsimd.py
 - sudo mkdir /var/run/snmpsim
 - sudo python snmpsim/snmpsimd.py --data-dir=tests/snmp_data --process-user=nobody --process-group=nogroup --agent-udpv4-endpoint=127.0.0.1:161 --cache-dir=tests/snmp_data &

script:
 - snmpwalk -v2c -c cisco 127.0.0.1