language: python
python:
  - 3.8

jobs:
  include:
    - os: windows
      language: shell
      env:
        - BUILD_LANG=NO
    - os: windows
      language: shell
      env:
        - BUILD_LANG=SE

    - os: linux
      env:
        - BUILD_LANG=NO
    - os: linux
      env:
        - BUILD_LANG=SE

  allow_failures:
    - os: windows

script:
  - echo $BUILD_LANG
