language: php
matrix:
  fast_finish: true
  include:
    - php: 7.4
addons:
 apt:
  packages:
   - mitmproxy

before_script:
 - (mitmdump -s proxy.py -p 9002 -v &)
script:
 - curl --head -x localhost:9002 http://requests-php-tests.herokuapp.com/get