dist: xenial
language: python

addons:
 apt:
  packages:
   - snmp


before_script:
 - sudo pip install snmpsim
 - sudo which snmpsimd.py
 - sudo mkdir /var/run/snmpsim
 - sudo snmpsimd.py --data-dir=tests/snmp_data --process-user=nobody --process-group=nogroup --agent-udpv4-endpoint=127.0.0.1:161 --daemonize

script:
 - snmpwalk -v2c -c public 127.0.0.1