language: php
matrix:
  fast_finish: true
  include:
    - php: 7.4
addons:
 apt:
  packages:
   - mitmproxy

before_script:
 #- start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --exec /usr/bin/mitmdump -- -s proxy.py -p 9002 -v
 - output = $(mitmdump -s proxy.py -p 9002 -v) || exit $?
 - echo $output
script:
 - curl --head -x localhost:9002 http://requests-php-tests.herokuapp.com/get