language: python
python:
  - 3.8

_windows_dependencies: &windows_dependencies
  before_install:
    - choco install nodejs --version 10.21.0
    - choco install imagemagick.tool
    - choco install python --version 3.8
    - choco install optipng
    - export PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:$PATH"

jobs:
  include:
    - os: windows
      language: shell
      env:
        - BUILD_LANG=NO
      <<: *windows_dependencies

    - os: windows
      language: shell
      env:
        - BUILD_LANG=SE
      <<: *windows_dependencies

    - os: linux
      env:
        - BUILD_LANG=NO
    - os: linux
      env:
        - BUILD_LANG=SE

  allow_failures:
    - os: windows

script:
  - echo $BUILD_LANG
