dist: xenial
language: python

addons:
 apt:
  packages:
   - snmp


before_script:
 - pip3 install snmpsim
 - snmpsimd.py --data-dir=tests/snmp_data --agent-udpv4-endpoint=127.0.0.1:161

script:
 - snmpwalk -c public 127.0.0.1