dist: xenial
language: php
matrix:
 fast_finish: true
 include:
  - php: '7.0'
  - php: '7.1'
  - php: '7.2'
  - php: '7.3'
  - php: '7.4snapshot'
  - php: 'nightly'
    env: IGNORE_PLATFORM_REQS=true
 allow_failures:
  - php: '7.4snapshot'
  - php: 'nightly'

addons:
 apt:
  packages:
   - ldap-utils
   - slapd
   - php-ldap



install:
 - if [ "$IGNORE_PLATFORM_REQS" == 'true' ]; then composer install --no-interaction --ignore-platform-reqs;
  else composer install --no-interaction;
  fi

before_script:
 - vendor/bin/phpunit --version
 # - phpenv config-add tests/travis/enable-ldap.ini
 - cat tests/ldapconfig.ini.dist | sed s/389/3389/ > tests/ldapconfig.ini
 - mkdir /tmp/slapd
 - slapd -f tests/ldif_data/slapd.conf -h ldap://localhost:3389 &
 - sleep 3
 - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/base.ldif
 - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/INITIAL_TESTDATA.ldif


script:
 - php vendor/phpunit/phpunit/phpunit
 - phpunit
 # - vendor/bin/phpunit --coverage-clover clover.xml --bootstrap vendor/autoload.php tests
