dist: bionic
language: python
python: 3.6

addons:
 apt:
  packages:
   - snmp
   #- python3-pip
services:
 - docker

before_install:
 - docker pull tandrup/snmpsim
 - docker run -d -v ./tests/snmp_data:/usr/local/snmpsim/data -p 161:161/udp tandrup/snmpsim

script:
 - snmpwalk -v2c -c cisco 127.0.0.1