dist: bionic
language: python
python: 3.6

addons:
 apt:
  packages:
   - snmp
   #- python3-pip

install:
 - git clone https://github.com/etingof/snmpsim.git

before_script:
 - pip install snmpsim
 - cd snmpsim
 - python setup.py install
 - SIM_BIN=$(which snmpsimd.py)
 - PYTHON_BIN=(which python)
 - which snmpsimd.py
 #- sudo -H pip3 install snmpsim
 #- sudo which snmpsimd.py
 #- sudo mkdir /var/run/snmpsim
 - sudo $PYTHON_BIN $SIM_BIN --data-dir=tests/snmp_data --process-user=nobody --process-group=nogroup --agent-udpv4-endpoint=127.0.0.1:161 --cache-dir=tests/snmp_data &

script:
 - snmpwalk -v2c -c cisco 127.0.0.1