language: sh
os: windows

before_install:
  # - choco upgrade chocolatey
  - choco install python
  #- choco install pywin32
  #- python -m pip install pyinstaller
  #- PYEXE = $ChocolateyInstall/bin/python.exe
  - cmd.exe //c "RefreshEnv.cmd"
  - export PATH="$ChocolateyInstall/bin:$PATH"
install:
  #- python -m pip install pywin32
  - python -V
  - where python
  - python -m pip install pyinstaller
  - pip install pywin32