language: python
python:
  - 3.8
os:
  - windows
  - linux
jobs:
  include:
    - os: windows
      language: shell

  allow_failures:
    - os: windows

env:
  matrix:
    - BUILD_LANG=NO
    - BUILD_LANG=SE

script:
  - echo $BUILD_LANG
