language: php
matrix:
  fast_finish: true
  include:
    - php: 7.4
services:
  - docker

install:
  - cd proxy
  - chmod +x start_docker.sh
  - ./start_docker.sh

script:
  - curl --head -x localhost:9002 http://requests-php-tests.herokuapp.com/get