language: python
python:
  - 3.8
matrix:
  include:
    - os: windows
      language: sh
    - os: linux

  allow_failures:
    - os: windows

env:
  matrix:
    - BUILD_LANG=NO
    - BUILD_LANG=SE

script:
  - echo $BUILD_LANG
