language: python
python:
  - 3.8
jobs:
  include:
    - os: windows
      language: sh
    - os: linux

  allow_failures:
    - os: windows

env:
  matrix:
    - ISO=$ISO_NO BUILD_LANG=NO
    - ISO=$ISO_SE BUILD_LANG=SE

script:
  - echo $BUILD_LANG
