language: sh
os: windows

before_install:
  - choco upgrade chocolatey
  - choco install python
  #- choco install pywin32
  #- python -m pip install pyinstaller
install:
  #- python -m pip install pywin32
  - python -V
  - where python
  - dir %ChocolateyInstall%\bin
  # - set
